openapi: 3.2.0
info:
  description: '# Introduction

    Esper APIs are a set of REST-based APIs that help you programmatically control and monitor Android-based Dedicated Devices running the Esper agent using Esper Manage.'
  version: 1.0.0
  title: ESPER API REFERENCE Group Commands API
  termsOfService: https://esper.io/terms-of-service
  contact:
    email: developer@esper.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://foo-api.esper.cloud/api
tags:
- name: Group Commands
  description: APIs to run group commands. Command will be run on all the active devices in a group
  externalDocs:
    description: Find out more in `Actions` of group commands
    url: https://docs.esper.io/home/console.html#groups
paths:
  /enterprise/{enterprise_id}/devicegroup/{group_id}/command/:
    parameters:
    - name: enterprise_id
      in: path
      description: ID of the enterprise
      required: true
      schema:
        type: string
        format: uuid
    - name: group_id
      in: path
      description: ID of the group
      required: true
      schema:
        type: string
        format: uuid
    post:
      summary: Run commands on group devices
      description: Fire commands on all the group devices. Deprecated in favour of commands V2.
      deprecated: true
      operationId: runGroupCommand
      responses:
        '201':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GroupCommand'
      security:
      - apiKey: []
      tags:
      - Group Commands
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GroupCommandRequest'
        description: Group command request
        required: true
  /enterprise/{enterprise_id}/devicegroup/{group_id}/command/{command_id}/:
    parameters:
    - name: command_id
      in: path
      description: A UUID string identifying this device command.
      required: true
      schema:
        type: string
        format: uuid
    - name: group_id
      in: path
      description: A UUID string identifying this group.
      required: true
      schema:
        type: string
        format: uuid
    - name: enterprise_id
      description: A UUID string identifying enterprise.
      in: path
      required: true
      schema:
        type: string
        format: uuid
    get:
      operationId: getGroupCommand
      summary: Get group command status
      description: Returns GroupCommand instance. Deprecated in favour of commands V2.
      deprecated: true
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GroupCommand'
      security:
      - apiKey: []
      tags:
      - Group Commands
components:
  schemas:
    GroupCommandEnum:
      type: string
      description: 'Group Command Options


        ```

        * REBOOT: Reboot device

        * LOCK:  Lock device screen

        * INSTALL:  Install an app on device

        * UPDATE_HEARTBEAT: Ping Device

        ```

        '
      enum:
      - REBOOT
      - LOCK
      - INSTALL
      - UPDATE_HEARTBEAT
    GroupCommand:
      required:
      - command
      - enterprise
      - group
      type: object
      properties:
        id:
          title: Id
          type: string
          format: uuid
          readOnly: true
        schedule:
          title: Schedule
          type: string
        command:
          $ref: '#/components/schemas/GroupCommandEnum'
        command_args:
          $ref: '#/components/schemas/GroupCommandArgs'
        state:
          title: State
          type: string
          enum:
          - Command Initiated
          - Command Success
          - Command Failure
          - Command Scheduled
        details:
          title: Details
          type:
          - string
          - 'null'
        created_on:
          title: Created on
          type: string
          format: date-time
          readOnly: true
        updated_on:
          title: Updated on
          type: string
          format: date-time
          readOnly: true
        is_active:
          title: Is active
          type: boolean
        enterprise:
          title: Enterprise
          type: string
          format: url
        group:
          title: Group
          type: string
          format: url
        issued_by:
          title: Issued by
          type:
          - string
          - 'null'
          format: uri
    GroupCommandArgs:
      title: Command args
      type: object
      properties:
        app_version:
          type: string
    GroupCommandRequest:
      required:
      - command
      type: object
      properties:
        command_args:
          $ref: '#/components/schemas/GroupCommandArgs'
        command:
          $ref: '#/components/schemas/GroupCommandEnum'
  securitySchemes:
    apiKey:
      description: "#### API KEY - Access Token\nAccess token for APIs passed as authorization header in calls. You need to generate this from your Esper Dev Console at `<domain>-api.esper.cloud` where foo is the sub-domain name you gave for your Esper Dev environment when you signed up for your Esper Dev account. Please follow the instructions [here](https://docs.esper.io/home/module/genapikey.html) to generate an access token.\nOnce you have the access token, you need to send an authorization header as below\n\n```bash\n\n    curl -X GET \\\n      https://<domain>-api.esper.cloud/api/enterprise/<enterprise_id>/device/ \\\n      -H 'Authorization: Bearer <ACCESS_TOKEN>' \\\n      -H 'Content-Type: application/json' \\\n```\n\n> Please note the use of keyword **Bearer** before the token value.\n\n\nYou can read more about api key authentication scheme [here](https://console-docs.esper.io/API/generate.html).\n"
      name: Authorization
      type: apiKey
      in: header
x-tagGroups:
- name: API Reference
  tags:
  - Enterprise
  - Application
  - Application V1
  - Device
  - Device Group
  - Commands
  - Group Commands
  - Token
  - Commands V2
  - Enterprise Policy
  - Geofence
  - Reports
  - Subscription
  - Content
